### ISSUE TITLE
Few Issues 

### ISSUE THREAD

**Issue by harishsai** [CruGlobal/ansible-oracle-psu#2]
Hi Pro,

First of all thanks for the project. I ran it and have few suggestions.

what is the use of ansible_check_mode? It was throwing errors after i removed it worked.
When the run book is run after applying patch it is shutting down the databases. Can you keep a check if patch is already applied and then shutdown the database.
run_once: true is only doing this on only one host. For eg: It did not create patch directory in second server for unzipping. It did not apply datapatch on second server as well.
Last but not least. It would be great if you could elaborate the read me or make a blog post so that others may use your code in a easier way. Read me is very short and few may not understand especially guys like me :) hehe.. I really appreciate your sincere efforts and expecting more from you.. Cheers mate.
Thanks,

Harish

**Comment by davidhollenberger** [comment]
Hi Harish,

Thanks for the comments.  This is definitely a work in progress and there are many rough edges to be worked on. 

More information on `ansible_check_mode` can be found here: http://docs.ansible.com/ansible/latest/playbooks_checkmode.html#information-about-check-mode-in-variables

The `run_once` issue you mention may be specific to my setup.  The files are extracted on shared storage so we only need that step run once for all nodes to be able to access them.

I agree with the need for better documentation.  I hope to be able to spend some time on that soon.

I appreciate the feedback!

- David

**Comment by harishsai** [comment]
Thank you.
